extends:
  - standard-with-typescript
  - prettier
overrides:
  - files: "*.ts"
    parserOptions:
      project: ./tsconfig.json
    rules:
      "@typescript-eslint/no-unused-vars":
        - error
        - argsIgnorePattern: "^_"
          varsIgnorePattern: "^_"
