RawInvoicePdfBucket:
  Type: AWS::S3::Bucket
  Properties:
    AccessControl: Private
    PublicAccessBlockConfiguration:
      BlockPublicAcls: true
      BlockPublicPolicy: true
      IgnorePublicAcls: true
      RestrictPublicBuckets: true
    BucketEncryption:
      ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: aws:kms
            KMSMasterKeyID: !GetAtt KmsKey.Arn
    VersioningConfiguration:
      Status: Enabled
    LoggingConfiguration:
      DestinationBucketName: !Ref RawInvoicePdfLogBucket
      LogFilePrefix: raw-invoice-pdf-bucket-log

RawInvoicePdfLogBucket:
  # checkov:skip=CKV_AWS_18: This is the config log bucket - no need for another  ***** what does this mean?
  Type: AWS::S3::Bucket
  Properties:
    VersioningConfiguration:
      Status: Enabled
    AccessControl: LogDeliveryWrite
    PublicAccessBlockConfiguration:
      BlockPublicAcls: true
      BlockPublicPolicy: true
      IgnorePublicAcls: true
      RestrictPublicBuckets: true
    BucketEncryption:
      ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: aws:kms
            KMSMasterKeyID: !GetAtt KmsKey.Arn

Outputs: # Outputs section declares output values that you can import into other stacks, return in response (to describe stack calls), or view on the AWS CloudFormation console.
  RawInvoicePdfBucketName:
    Description: Name of the raw pdf bucket
    Value: !Ref RawInvoicePdfBucket
  RawInvoicePdfLogBucketName:
    Description: Name of the raw pdf log bucket
    Value: !Ref RawInvoicePdfLogBucket
